// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABBC7x3S39zZmludRIU8kNX2yico-nVzE',
    appId: '1:417831327586:web:f3da3dd0a66717af2ebe3b',
    messagingSenderId: '417831327586',
    projectId: 'auditcloud-45700',
    authDomain: 'auditcloud-45700.firebaseapp.com',
    storageBucket: 'auditcloud-45700.firebasestorage.app',
    measurementId: 'G-5TSWJZN930',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsnoOp1aZCDwssFuGGv0MYQA-s3G681bE',
    appId: '1:417831327586:android:c778cbbef76baa5e2ebe3b',
    messagingSenderId: '417831327586',
    projectId: 'auditcloud-45700',
    storageBucket: 'auditcloud-45700.firebasestorage.app',
  );
}
